# Generated by Django 5.2.11 on 2026-02-23 13:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('location_found', models.CharField(max_length=200)),
                ('date_found', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('found', 'Found'), ('claimed', 'Claimed'), ('expired', 'Expired')], default='found', max_length=20)),
                ('photo_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LostReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('student_email', models.EmailField(max_length=254)),
                ('item_name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_lost', models.DateTimeField(default=django.utils.timezone.now)),
                ('location_lost', models.CharField(blank=True, max_length=200)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
        ),
    ]
