# Generated by Django 5.2.11 on 2026-02-24 14:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_and_found', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_id', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='founditem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='founditem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='found_items/'),
        ),
        migrations.AddField(
            model_name='founditem',
            name='reported_by_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='lostreport',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='ItemReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_name', models.CharField(max_length=200)),
                ('reporter_email', models.EmailField(max_length=254)),
                ('item_name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('location_found', models.CharField(max_length=200)),
                ('date_found', models.DateTimeField(default=django.utils.timezone.now)),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('converted_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_report', to='lost_and_found.founditem')),
            ],
        ),
        migrations.CreateModel(
            name='PickupSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('student_email', models.EmailField(max_length=254)),
                ('pickup_date', models.DateField()),
                ('time_slot', models.CharField(choices=[('09:00', '9:00 AM – 10:00 AM'), ('10:00', '10:00 AM – 11:00 AM'), ('11:00', '11:00 AM – 12:00 PM'), ('13:00', '1:00 PM – 2:00 PM'), ('14:00', '2:00 PM – 3:00 PM'), ('15:00', '3:00 PM – 4:00 PM'), ('16:00', '4:00 PM – 5:00 PM')], max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('found_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='lost_and_found.founditem')),
            ],
        ),
    ]
