# Generated by Django 5.2.11 on 2026-02-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_and_found', '0002_userprofile_founditem_created_at_founditem_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
