# Generated by Django 5.2.11 on 2026-02-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_and_found', '0003_userprofile_email_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemreport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='found_items/'),
        ),
    ]
