# Generated by Django 5.2.11 on 2026-02-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_and_found', '0004_itemreport_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditem',
            name='custody_status',
            field=models.CharField(choices=[('office', 'University Office'), ('finder', 'With Finder')], default='finder', max_length=20),
        ),
        migrations.AddField(
            model_name='itemreport',
            name='custody_status',
            field=models.CharField(choices=[('office', 'University Office'), ('finder', 'With Finder')], default='finder', max_length=20),
        ),
    ]
