# Generated by Django 6.0.3 on 2026-03-28 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_and_found', '0006_claimrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostreport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lost_items/'),
        ),
        migrations.AddField(
            model_name='lostreport',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
